### ISSUE TITLE
full  example how to use this api to receive and send messages

### ISSUE THREAD

**Issue by wanghaisheng** [dib0/NHapiTools#1]
can u provide full  example how to use this api to receive and send messages

**Comment by dib0** [comment]
Hi!

There are examples on my blog:
http://dib0.nl/component/search/?searchword=nhapitools&ordering=popular&searchphrase=any&areas[0]=tortags

Using nhapitools isn't that different from using nhapi. It just adds functionality or simplifies it. Chec these posts:
http://dib0.nl/component/search/?searchword=nhapi%20hl7&ordering=popular&searchphrase=any&areas[0]=tortags

On the other hand, you might want to have a look at my other project HL7Fuse. This handles a lot of the network communication and might give your project a kickstart:
https://github.com/dib0/HL7Fuse

**Comment by Anacronos** [comment]
Links are dead
