### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by pelnarp** [dib0/NHapiTools#10]
Hi, is there any documentation for this library? I have found some links to your legacy blog which does not exist any more. I tried to follow the examples such as this one:

foreach (ORU_R01_PATIENT_RESULT patient in oMessage.GetAllPATIENT_RESULTRecords())
{
    PID pid = patient.PATIENT.PID;
    
    foreach (CX alternateId in pid.GetAlternatePatientIDPIDRecords())
    {
        // do something with the alternate ID
    }
}

However I am not even sure how to convert a parsed IMessage  created like this:

PipeParser parser = new PipeParser();
            IMessage m = parser.Parse(stringMessage);

into ORU_R01 class which GetAllPATIENT_RESULTRecords() method needs

**Comment by dib0** [comment]
Hi,

Casting the IMessage can be done by using the NHapi.V2x library. You should choose the right version that belongs to the HL7 version that you are parsing:

using NHapi.Model.V23.Message;
ADT_A08 a08msg = (ADT_A08)msg;
Or:
ADT_A08 a08msg = msg as ADT_A08;

This is how the NHapi project works (this project is just an addon to that project: https://github.com/duaneedwards/nHapi/).
There's a small guide on how to work with NHapi: https://www.smashwords.com/books/view/344824
The example code from the book can be found here:
https://github.com/dib0/NHapiExampleApp

Also this project might be helpfull (depending on the case you are working on):
https://github.com/dib0/HL7Fuse
