### ISSUE TITLE
SimpleMLLPClient

### ISSUE THREAD

**Issue by sebastianoscarlopez** [dib0/NHapiTools#12]
Hi dib0
I need send OML messages. I bought the book thinking, because I had think this maybe contains an example. I had searched for all documentation of NHapiTools and HL7Fuse, but I found nothing.

Please, would you want to give an example?

note: The blog of you doesn't work

**Comment by dib0** [comment]
Hi Sebastiano,

What kind of example are you looking for?

I have some generic examples, for example from the book, here:
https://github.com/dib0/NHapiExamples
https://github.com/dib0/NHapiExampleApp

Of course the HL7Fuse and NHapiTools are project that can help you. I don't have any specific examples that use OML messages, but in essence they aren't that different from other HL7 messages. The tools you need greatly depend on the use case(s) you have.

I hope these examples help! If you have any questions where I might be able to help, please let me know.

**Comment by sebastianoscarlopez** [comment]
Hi Bas Van Den Berg, thanks for you reply,

I had developed a service for message receive from Mirth using HL7Fuse,
HL7Fuse's great!!! and his documentation was me enought.

Now, I'm looking for an example of message send with either HL7Fuse or
Supersocket or SImpleMLLP or similar.

Thanks for advance.

**Comment by dib0** [comment]
Hi!

Good to hear that HL7Fuse was helpfull!! :-)

If you just need to send a HL7 message I would choose to use the NHapiTools SimpleMLLP client.You might be able to copy some of the code from the examples. The usage of the SimpleMLLP client is quit simple, just build a connection and send the HL7 message through it.
