### ISSUE TITLE
Incorrect message structure for Acks generated with MakeACK

### ISSUE THREAD

**Issue by MightyJudge** [dib0/NHapiTools#18]
There appears to be an issue in the MakeACK method causing it to create invalid Acks when the message structure (MSH-9-3) field is populated in the incoming message.

As the MSH segment is copied from the inbound message to the ACK and MSH-9-3 is not updated Acks generated from an incoming message that had MSH-9-3 populated will also have MSH-9-3 populated. As Ack’s always have a differing structure to the inbound message this in not valid.

**Comment by dib0** [comment]
I solved it by clearing the MSH-9-3 field. It will be included in the next release.
