### ISSUE TITLE
Nuget version not aligned

### ISSUE THREAD

**Issue by holpit** [dib0/NHapiTools#19]
Hi,
the nuget version isn't aligned with code.
The nHapi dependency is 2.5.0.6 in nuget site,  but nHapi.Core 2.6.0.2 in code for .netStandard 2.0 (this is correct)

Nuget
.NETFramework 4.6.1
nHapi (>= 2.5.0.6)
System.Configuration.ConfigurationManager (>= 5.0.0)
.NETStandard 2.0
NETStandard.Library (>= 2.0.0)
nHapi (>= 2.5.0.6)
System.Configuration.ConfigurationManager (>= 5.0.0)

Code
```
    <dependencies>
      <group targetFramework=".NETFramework4.6.1">
        <dependency id="nHapi" version="2.5.0.6" />
        <dependency id="System.Configuration.ConfigurationManager" version="5.0.0" />
      </group>
      <group targetFramework=".NETStandard2.0">
        <dependency id="nHapi.Core" version="2.6.0.2" />
        <dependency id="NETStandard.Library" version="2.0.0" />
        <dependency id="System.Configuration.ConfigurationManager" version="5.0.0" />
    </group>
    </dependencies>
```

Can you publish an updated nuget package?

Thank you.

**Comment by dib0** [comment]
Ok, I've updated the dependecies, like you proposed and published a new packages. Hope this will work better!
